project:
  type: website

website:
  title: "Supermarket list"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      dark: cyborg
      light: cosmos

    css: styles.css
    toc: true



